### ISSUE TITLE
Issue with altering application context

### ISSUE THREAD

**Issue by HarshaSuranjith** [spring-roots/application-context-deep-dive#1]
Hi @jtigger @pivotaljohn,

Thanks you very much for your effort in developing this very insightful guide for understanding the spring internals.

I am having an issue accessing lifecycle methods such as refresh(), close() and regisrer..() methods in the application. What should I do to alter the application context at runtime ??

`public class ApplicationContextApp {

    public static void main(String[] args) {
        //ApplicationContext context = new ClassPathXmlApplicationContext("application-context.xml");
        ApplicationContext context = new StaticApplicationContext();
        context.getApplicationName();
        MessageSource messageSource = (MessageSource) context.getBean("messageSource");
        Probe p = context.getAutowireCapableBeanFactory().createBean(Probe.class);
        System.out.println(Arrays.toString(context.getBeanDefinitionNames()));

        ApplicationContext annotationContext = new AnnotationConfigApplicationContext();
        System.out.println(annotationContext.getApplicationName());
        System.out.println(Arrays.toString(annotationContext.getBeanDefinitionNames()));
    }

}`

This is a snippet of my code and all the getters are available, but not the setters or functions that would modify the application context. Any help on this is much appreciated.

Thanks very much again.

**Comment by pivotaljohn** [comment]
Hi @HarshaSuranjith.  I apologize for not seeing your issue before today.

Do I understand your question correctly: the you want to be able to add or remove beans after the application context has been started?

Or are you talking about wanting to learn how to programmatically register beans with the application context _before_ it is being started?

**Comment by HarshaSuranjith** [comment]
Thanks very much. I made a mistake in the code. And I am really sorry for troubling. 
Awesome tutorial.

**Comment by pivotaljohn** [comment]
Sounds like you've found your way... great to hear!  Sounds like you got something out of the tutorial; that's delightful.  I'm sure you've run into parts that could be better, feel free to send me your constructive critiques.

Happy Hacking!
